application: future-infra
version: 1
runtime: python
api_version: 1

default_expiration: "10d"

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.py
  login: required

- url: /.*
  script: main.py

